### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by sugo71** [vanwijkdave/QuitAll#1]
XR 13.3 u0 4.2.1
Not working, "Clear"-Button is viewable for 0.2 seconds, than its vanished (equal left or right top). Prefs working now

**Comment by vanwijkdave** [comment]
Are you using any tweaks for the app switcher?

**Comment by sugo71** [comment]
Not at all. But I can imagine it has something to do with PerfectTimeXS or BatteryPercentX. 
Tweaks:
7-zip (POSIX): 16.02-1
A-Font: 1.5
AppList: 1.5.15~beta1
AppStore++: 0.9.8-9
AppSync Unified: 70.0
APT (apt-key): 1.8.2-1
APT (libapt-pkg): 1.8.2-1
APT 1.4 Transitional: 1:0
APT Strict (lib): 1.8.2-1
APT: 1.8.2-3
Assuan: 2.5.1-1
Base Structure: 1-5
Batchomatic: 4.3.1
BatteryPercentX [Public]: 1.4.1-33
Berkeley DB: 6.2.32-1
BigBoss Icon Set: 1.0
Bourne-Again SHell: 5.0.3-2
bzip2: 1.0.6-1
CA Certs: 0.0.2
CarBridge (iOS 13): 1.0.2
CCSupport: 1.2.2
Central: 1.0.1
Cephei: 1.14
CocoaTop: 2.0.2
Core Utilities (/bin): 8.31-1
Core Utilities: 8.31-1
Cydia Installer: 1.1.32~b23
Cydia Translations: 1.1.32~b1
Darwin Tools: 1.1-1
Debian Packager: 1.19.7-1
Debian Utilities: 4.8.6-1
debugserver-10: 10.0.0~svn-20191106+dcaf932-1
debugserver: 10-1
DeleteCut: 0.4
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
Erica Utilities: 1:0.4.2
file: 5.35-2
Filza File Manager 64-bit: 3.7.4-12
Find Utilities: 4.6.0-2
Flame: 1.3
FloatyDock: 2.1
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
grep: 3.1-1
gzip: 1.9-1
HapticKeys: 4.0-3
iCleaner Pro: 7.8.0
IconSupport: 1.11.1
IconSupportFix: 1.0.0
iOS Firmware: 13.3
iPhone Firmware (/sbin): 0-1
Jailbreak Resources: 1.0~b27
jbctl: 0.2.3-1
KSBA: 1.3.5-1
Launch Daemon Controller: 23-1
libclang-cpp10: 10.0.0~svn-20191106+dcaf932-1
libcolorpicker: 1.6.7
libCSColorPicker: 1.0.3
libCSPreferences: 1.2.9
libidn2: 6.1.2-1
libllvm10: 10.0.0~svn-20191106+dcaf932-1
libplist: 2.0.0-2
libSparkAppList: 1.0.4
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.2+24497ae-1
Locale Profiles in UTF-8: 1.0-1
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
MiDevice: 2.0.0-3
Nettle: 3.4.1-1
New Curses: 5.9-1
New Curses: 6.1+20181013-1
New GNU Portable Threads: 1.6-1
NewTerm (iOS 10 – 13): 2.4
NoAnimationsX: 1.0
NoDNDBanner: 0.0.1
NtSpeed: 0.2~beta7
OpenSSH: 8.1-1
OpenSSL 1.0 Libraries: 1.0.2s-1
OpenSSL 1.1.1 Libraries: 1.1.1c-1
p11-kit: 0.23.12-1
PerfectTimeXS: 0.2.1-2
PowerSelector (iOS 11 to 13): 1.2.6
PreferenceLoader: 2.2.4
Profile Directory: 0-1
QuitAll: 1.0.1
readline: 8.0-1
ReProvision: 0.5.2~EOL
RocketBootstrap: 1.0.7~beta3
Safari Plus: 1.7.10-2
sed: 4.5-1
Shadow: 2.0.20
shell-cmds: 118-8
shuffle: 1.1.0
Sposify: 3.1.4
StrongerFi12: 1.0.0~beta5
Substitute Support Package: 0.1~b3
Substrate Safe Mode: 0.9.6003
SwipeSelection: 1.5.6
System Info: 2.3.3-2+debug
System Memory Reset Fix: 2.0
system-cmds: 790.30.1-2
Tape Archive: 1.30-2
Trust Cache Injector: 0.4~b5
Twitter No Ads: 0.0.2
UIKit Tools: 1.1.15-2
unrar: 5.6.4-1
unzip: 6.0+deb9u1-1
XZ Utils: 5.2.4-4
Zebra: 1.1~beta2-1
zip: 2.32-1

**Comment by sugo71** [comment]
Dunno why half of the tweaks are scored out...some kind of copy&paste-error

**Comment by ConorTheDev** [comment]
Disable all tweaks apart from QuitAll and enable other ones one at a time until the issue arises

**Comment by sugo71** [comment]
ok...it‘s FloatyDock. Any suggestions?

**Comment by vanwijkdave** [comment]
delete FloatyDock?, or try disable some floatydock settings

**Comment by sugo71** [comment]
Disabled the slide over and split view-option,now the close button is visible again...strange.
