### ISSUE TITLE
No button when launching multitask from Apps pages

### ISSUE THREAD

**Issue by MaceUD** [vanwijkdave/QuitAll#11]
Hi, 

When I launch the multitask from nowhere (I lost the name, basically from where you chose the app you want to launch 😅), I have no Quit All button.
It works well if I launch the multitask from any app.

Thanks for the tweak!
Best regards

**Comment by SarahH12099** [comment]
Yep, was able to confirm the same problem, Here is the info of my idevice: iOS 14.2 iPhone 8 Plus, Odysseyra1n

**Comment by vanwijkdave** [comment]
Should be solved
