### ISSUE TITLE
Clear button problem

### ISSUE THREAD

**Issue by BryanBzm** [vanwijkdave/QuitAll#5]
Hey! On my iPhone (iPhone 8 on iOS 13.3.1), the clear button doesn’t appear when i come in the switcher from homescreen, I can only see it when i come from an app (see screenshots for both cases) but even when not visible, I can click on it and it kill all apps.

BTW the button is no at the right place, it overcomes on the top bar (status bar activated in the switcher with statusswitcher tweak)

I guess there is this problem because I don’t have an iphone X format, you may have to move it on my screen version, just a bit to allow us to have the bar on the switcher and your tweak at the same time to appreciate both of the tweak (StatusSwitcher and QuitAll).

Thanks for reading and obviously for your work, simple elegant tweak, I’m hopping you could deal with that and update your tweak!
Goodbye!!

![C7126300-6E52-43F3-A221-D70798805C79](https://user-images.githubusercontent.com/62108869/76535816-c78ec900-647b-11ea-92f4-13253fb0eb2a.png)
![C1017DE7-3151-47BA-B7C3-A2DEBE12231D](https://user-images.githubusercontent.com/62108869/76535831-cd84aa00-647b-11ea-99a1-ded85997c39c.png)

**Comment by billxsand** [comment]
Same issue here

I hadn’t noticed that it works in apps, I thought it was just unstable. Thanks

**Comment by maxexcloo** [comment]
Same issue on iPhone 7 Plus unfortunately!

**Comment by vanwijkdave** [comment]
should be fixed as of latest version
