### ISSUE TITLE
no button shown on iPad Pro 11"

### ISSUE THREAD

**Issue by MikeMiller477** [vanwijkdave/QuitAll#7]
According to description it should work also on iPad.
But there is no button shown, regardeless if it should be shown left or right and screen orientation.

**Comment by shayshtern** [comment]
True, any update?

**Comment by Irwan-png** [comment]
> According to description it should work also on iPad.
> 
> But there is no button shown, regardeless if it should be shown left or right and screen orientation.
> 
> incaran e

**Comment by Assfugil** [comment]
same I am on iPad Pro 9.7"

**Comment by vanwijkdave** [comment]
Should be solved as of latest update
